### ISSUE TITLE
Problem when updating

### ISSUE THREAD

**Issue by Xoas** [BlackTasty/Osmo#19]
**Describe the bug**
When you run for the first time after updating, the program crashes.

**To Reproduce**
1. Go to 'Show/Hide updater'
2. Use localhost to apply the fake update (e.g.: change version to 0.0.4.150 or newer, and runtime.zip)
3. Click on '_DOWNLOAD'
4. Click on '_RESTART'
5. See error
[24-12-2018_00-33-51_osmo_crashlog.txt](https://github.com/BlackTasty/Osmo/files/2706680/24-12-2018_00-33-51_osmo_crashlog.txt)

**Comment by BlackTasty** [comment]
I just looked into this, seems like Osmo keeps a file lock on old files for a short amount of time after clicking restart. This in turn crashes the new instance while trying to delete these locked files.
I'll release an update tomorrow regarding this issue ;) 

But I wonder, why is Osmo using localhost on your system?

**Comment by Xoas** [comment]
I wanted to see what context it was in so that I could translate without errors and what it would look like in the UI, that and at the same time check whether the auto-update function works without problems.
