### ISSUE TITLE
'Replace Element' Shortcut

### ISSUE THREAD

**Issue by terrdus** [BlackTasty/Osmo#3]
**Problem**
It's really painful when creating new skin ( or re-doing current ), to every time click on floating action button to replace some skin elements. If there are many elements you want to replace, it's taking too much time expanding a menu to get to replace element. 

**Solution**
Best would probably be registering keyboard shortcut, or if that is too much work, then making left-click menu available.

**Comment by BlackTasty** [comment]
Keyboard shortcuts are now implemented and added to the latest release ([v0.0.2.65-alpha](https://github.com/BlackTasty/Osmo/releases/tag/0.0.2.65-alpha)).

All shortcuts can be found under Settings -> Keyboard shortcuts -> Cheat sheet
