### ISSUE TITLE
Osmo v0.0.3.85-alpha does not run

### ISSUE THREAD

**Issue by Xoas** [BlackTasty/Osmo#4]
**Description**
No matter how hard you try to run it, it closes immediately, without even showing the interface.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download "Osmo v0.0.3.85-alpha" release or compile from source (from commit [6e1ebe4](https://github.com/BlackTasty/Osmo/commit/6e1ebe48960513d21cf00b856f4eb3df70d997ca) to [91f799d](https://github.com/BlackTasty/Osmo/commit/91f799db95266490fcb90e5245d049927432381a))
2. If compiled wait until "System.NotSupportedException: 'No imaging component suitable to complete this operation was found.'", if release version is downloaded wait until it disappears from the Task Manager list.

**Expected behaviour**
That the window will be displayed, or that it will show the exception produced, if a log is not automatically written.

**Screenshots**
Not taken for lack of disk space.

**Laptop:**
 - Windows version: Windows 10
 - Windows build version: 1803 (build 17134.137)

**Additional context**
None in specific, 4 GB of RAM and Intel Core i3-380M, maybe less than 1 GB of disk space.

**Comment by BlackTasty** [comment]
Can you send me the stacktrace of the crash? I'll try to reproduce this as soon as I get home

**Comment by Xoas** [comment]
Here [OSMO001.log](https://github.com/BlackTasty/Osmo/files/2179112/OSMO001.log).

**Comment by BlackTasty** [comment]
Seems like this is caused by one of your skins. You can try to move all skins out of your folder and then add them back one by one. 
If you find the skin which triggers this crash can you send it to me? This would help a lot :)

**Comment by Xoas** [comment]
No change, I also tried to install it (the Osmo v0.0.3.85-alpha release) on a machine that never had osu! as a clean program run (without settings.cfg), and it still closed and did not create the configuration file either.

**Comment by BlackTasty** [comment]
What you can do in the meantime is to go into the SkinElement class (located under Core -> Objects) and put this line in a try/catch block: 
> var bitmapFrame = BitmapFrame.Create(new Uri(Path, UriKind.Absolute), BitmapCreateOptions.DelayCreation, BitmapCacheOption.None);
> ImageSize = new Size(bitmapFrame.PixelWidth, bitmapFrame.PixelHeight);

In the catch block put
> ImageSize = new Size();

This should fix it.

**Comment by BlackTasty** [comment]
Also could you send me your skin folder? This way I can try to reproduce the error

**Comment by Xoas** [comment]
My skin folder is 1.4GB, and I do not even have space on the disk to compress it and send it, I'm just cleaning to make some space, I'll be able to try it tomorrow, for now I'll do what you suggested before updating the local repo.

**Comment by Xoas** [comment]
It works! but... I've been resizing the "paper osu!" skin, which has mostly HD elements to test the Resize Tool, but asks if the image inputoverlay-background@2x.png could be deformed, when I give it to proceed, it changes the image to another size and the color to black, likewise ask for reversearrow@2x.png and when I give it halve, Osmo is closed. I think it would be better to create another issue for this...

**Comment by Xoas** [comment]
I almost forgot to tell you, if you don't have the settings.cfg file with the osu! skins folder, Osmo still closes, with the change you suggested, but if it does, it takes a little longer to load but it does work.
Now I will update the repo to the commit of the logger implementation.

**Comment by BlackTasty** [comment]
Could you send me the two files which aren't working in the resize tool?

**Comment by Xoas** [comment]
Ok, #6.
