### ISSUE TITLE
Resize Tool bugs

### ISSUE THREAD

**Issue by BlackTasty** [BlackTasty/Osmo#6]
**Describe the bug**
Some images become black, others crash the application on resize.

**Expected behavior**
Images should be resized without changes to the content itself (only to it's size) and also Osmo shouldn't crash.

**Additional context**
Referenced in issue #4, but I need the images which cause these problems. My guess is that the image format makes these problems.

**Comment by Xoas** [comment]
[Here are the two files](https://puu.sh/AVdht/18614b3b9f.zip) that you asked for in #4, one was resized but Osmo closed after that... It is preferable to download the skin from [here](https://www.youtube.com/watch?v=7c57e0-A9Eo).

**Comment by BlackTasty** [comment]
Thank you, I'll take a look a it

**Comment by BlackTasty** [comment]
So I've tried it out myself and came to the following conclusion:
1. I think the reason why the image turns black instead of staying white is that the method I use may change the image format a bit, but it does nothing to the transparency itself. (both images are 100% transparent) You can even test it yourself, just open both images in an image editing software like Gimp or Photoshop:
   * Create a new layer and fill it with the opposite color (if the thumbnail is black fill it with white and vice versa)
   * Combine the transparent layer with the new layer and use a color picker. The result should be either black or white :)
2. The reason Osmo closes while resizing is that it crashes. The crash itself is triggered because another process has the file already opened, and my guess is that Osmo holds a file lock on the file and thus cannot override it. I am already working on a fix

**Comment by BlackTasty** [comment]
Can you try it again with the current commit? Osmo successfully resized all elements of the paper osu! skin on my computer
